# Generated by Django 5.0.6 on 2024-05-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_score', models.IntegerField(default=0)),
                ('home_score', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
